/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.DAO.Banco;
import Model.DAO.ClienteDAO;
import controller.ClienteController;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author danil
 */
public class Cliente extends javax.swing.JFrame {
    private final ClienteController controller;
    
    /**
     * Creates new form Cliente
     */
    public Cliente() throws SQLException {
        initComponents();
        this.controller = new ClienteController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        ComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TextDataNascimento = new javax.swing.JTextField();
        TextCEP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextRG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCliente = new javax.swing.JTable();
        BtnExcluir = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nome.setForeground(new java.awt.Color(255, 255, 255));
        Nome.setText("Nome:");
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        ComboBoxSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        getContentPane().add(ComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 290, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CEP:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        TextDataNascimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(TextDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 290, 30));

        TextCEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(TextCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 290, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Endereço:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        TextNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 290, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RG:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-mail:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        TextTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(TextTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 290, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefone:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        TextEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(TextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 290, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de Nascimento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        TextRG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRGActionPerformed(evt);
            }
        });
        getContentPane().add(TextRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 290, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        TextEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(TextEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 290, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));
        getContentPane().add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 120, 30));

        TableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sexo", "Data de nascimento", "Telefone", "E-mail", "RG", "Endereço", "CEP"
            }
        ));
        jScrollPane1.setViewportView(TableCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 830, 280));

        BtnExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnExcluir.setText("Excluir");
        getContentPane().add(BtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 80, 30));

        BtnSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, 30));

        BtnEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 920, 660));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/AgendaFundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRGActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        controller.salvarCliente();
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        try {
            Connection conexao = new Banco().getConnection();
            ClienteDAO clienteDAO = new ClienteDAO(conexao);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Cliente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JComboBox<String> ComboBoxSexo;
    private javax.swing.JLabel Nome;
    private javax.swing.JTable TableCliente;
    private javax.swing.JTextField TextCEP;
    private javax.swing.JTextField TextDataNascimento;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextRG;
    private javax.swing.JTextField TextTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private void iniciar() throws SQLException{
        this.controller.atualizaTabela();
    }
    public JTextField getTextCEP() {
        return TextCEP;
    }

    public void setTextCEP(JTextField TextCEP) {
        this.TextCEP = TextCEP;
    }

    public JTextField getTextDataNascimento() {
        return TextDataNascimento;
    }

    public void setTextDataNascimento(JTextField TextDataNascimento) {
        this.TextDataNascimento = TextDataNascimento;
    }

    public JTextField getTextEmail() {
        return TextEmail;
    }

    public void setTextEmail(JTextField TextEmail) {
        this.TextEmail = TextEmail;
    }

    public JTextField getTextEndereco() {
        return TextEndereco;
    }

    public void setTextEndereco(JTextField TextEndereco) {
        this.TextEndereco = TextEndereco;
    }

    public JTextField getTextID() {
        return TextId;
    }

    public void setTextID(JTextField TextID) {
        this.TextId = TextID;
    }

    public JTextField getTextNome() {
        return TextNome;
    }

    public void setTextNome(JTextField TextNome) {
        this.TextNome = TextNome;
    }

    public JTextField getTextRG() {
        return TextRG;
    }

    public void setTextRG(JTextField TextRG) {
        this.TextRG = TextRG;
    }

    public JTextField getTextTelefone() {
        return TextTelefone;
    }

    public void setTextTelefone(JTextField TextTelefone) {
        this.TextTelefone = TextTelefone;
    }

    public JTable getTableCliente() {
        return TableCliente;
    }

    public void setTableCliente(JTable TableCliente) {
        this.TableCliente = TableCliente;
    }

    public JComboBox<String> getComboBoxSexo() {
        return ComboBoxSexo;
    }

    public void setComboBoxSexo(JComboBox<String> ComboBoxSexo) {
        this.ComboBoxSexo = ComboBoxSexo;
    }
    
    
}
